const Map<String, String> weatherOperations = {
  'PAC0': 'Convective Precipitation',
  'PR0': 'Precipitation Intensity',
  'PA0': 'Accumulated Precipitation',
  'PAR0': 'Rain Map',
  'PAS0': 'Snow Map',
  'SD0': 'Depth of Snow',
  'WS10': 'Wind Speed at 10m',
  'WND': 'Wind Map',
  'APM': 'Atmospheric Pressure',
  'TA2': 'Air Temperature at 2m',
  'TD2': 'Dew Point Temperature',
  'TS0': 'Soil Temperature 0-10cm',
  'TS10': 'Soil Temperature >10cm',
  'HRD0': 'Relative Humidity',
  'CL': 'Cloudiness',
};
